### ISSUE TITLE
How to declare object MethodNode 

### ISSUE THREAD

**Issue by dat0825** [saeg/asm-defuse#10]
Hi, Anyone help me to create an object MethodeNode `MethodNode mn = ... // A regular MethodNode from ASM tree API`
Many Thanks!

**Comment by andrioli** [comment]
You can read the ASM [user guide](https://asm.ow2.io/asm4-guide.pdf). The tree API is covered on part II. This the best introduction for ASM that I know. The documentation is for ASM 4, but the API didn't change much in new versions.

For more information about ASM please refer to website https://asm.ow2.io/

**Comment by andrioli** [comment]
The following may help you

https://github.com/saeg/asm-defuse/blob/asm-defuse-0.0.6/src/test/java/br/usp/each/saeg/asm/defuse/validation/ValidationTestUtil.java

There you will find two methods: one to get a `ClassNode` from _classpath_ and another method to get a `MethodNode` from a `ClassNode`

You can use like this:

```java
getMethodNode(getClassNode(MyClass.class), "methodName", "()V");
```

**Comment by dat0825** [comment]
> The following may help you
> 
> https://github.com/saeg/asm-defuse/blob/asm-defuse-0.0.6/src/test/java/br/usp/each/saeg/asm/defuse/validation/ValidationTestUtil.java
> 
> There you will find two methods: one to get a `ClassNode` from _classpath_ and another method to get a `MethodNode` from a `ClassNode`
> 
> You can use like this:
> 
> ```java
> getMethodNode(getClassNode(MyClass.class), "methodName", "()V");
> ```

Thank you. I got it. I have a small question that the number of  `chain.def` and `chain.use` correspond in my code?
Example, I want get Definition-Use Chain from my fuction test like this:
```
public void test(int a, int b, int c) {
		a = 5;
		b = 3;
		if (a == 3) {
			a += 1;
		} else {
			c = a + b;
		}
	}

```
Output: the first def-use chain is `(1, (6,7), 1)`. What this mean?

**Comment by andrioli** [comment]
If you look at `DefUseChain` [class definition](https://github.com/saeg/asm-defuse/blob/asm-defuse-0.0.6/src/main/java/br/usp/each/saeg/asm/defuse/DefUseChain.java#L40-L46) you will find 4 fields (`def`, `use`, `target` and `var`).

The [current](https://github.com/saeg/asm-defuse/releases/tag/asm-defuse-0.0.6) version of ASM-DefUse does not map `DefUseChain` to source-code, but to the index in `MethodNode` instructions list (see MethodNode's JavaDoc [here](https://www.javadoc.io/static/org.ow2.asm/asm-tree/6.0/org/objectweb/asm/tree/MethodNode.html#instructions))

So, `def` is the index in instructions list that the definition of the variable occurs. Similarly, `use` is the index in instructions list that the use of the variable occurs. `var` is the index of the variable in the variable array ([`DefUseAnalyer.getVariables()`](https://github.com/saeg/asm-defuse/blob/asm-defuse-0.0.6/src/main/java/br/usp/each/saeg/asm/defuse/DefUseAnalyzer.java#L156-L158)).

When `use` is a [predicate instruction](https://github.com/saeg/asm-defuse/blob/asm-defuse-0.0.6/src/main/java/br/usp/each/saeg/asm/defuse/DefUseAnalyzer.java#L160-L171) the use of the variable is by definition associated with the branch, not with the instruction itself. In this case, `target` will be the index in instructions list of a successor of the predicate instruction. The value will be `-1` (undefined), otherwise.

**Comment by dat0825** [comment]
> If you look at `DefUseChain` [class definition](https://github.com/saeg/asm-defuse/blob/asm-defuse-0.0.6/src/main/java/br/usp/each/saeg/asm/defuse/DefUseChain.java#L40-L46) you will find 4 fields (`def`, `use`, `target` and `var`).
> 
> The [current](https://github.com/saeg/asm-defuse/releases/tag/asm-defuse-0.0.6) version of ASM-DefUse does not map `DefUseChain` to source-code, but to the index in `MethodNode` instructions list (see MethodNode's JavaDoc [here](https://www.javadoc.io/static/org.ow2.asm/asm-tree/6.0/org/objectweb/asm/tree/MethodNode.html#instructions))
> 
> So, `def` is the index in instructions list that the definition of the variable occurs. Similarly, `use` is the index in instructions list that the use of the variable occurs. `var` is the index of the variable in the variable array ([`DefUseAnalyer.getVariables()`](https://github.com/saeg/asm-defuse/blob/asm-defuse-0.0.6/src/main/java/br/usp/each/saeg/asm/defuse/DefUseAnalyzer.java#L156-L158)).
> 
> When `use` is a [predicate instruction](https://github.com/saeg/asm-defuse/blob/asm-defuse-0.0.6/src/main/java/br/usp/each/saeg/asm/defuse/DefUseAnalyzer.java#L160-L171) the use of the variable is by definition associated with the branch, not with the instruction itself. In this case, `target` will be the index in instructions list of a successor of the predicate instruction. The value will be `-1` (undefined), otherwise.

So, If I put my data in my method, ASM support show the list index instructions that it run ? Example, I call method `test(a,2,3)` and my expect output is a executive path.

**Comment by andrioli** [comment]
No, we do not output a possibly executed path for a given input.

**Comment by dat0825** [comment]
> No, we do not output a possibly executed path for a given input.
Yes! Thanks for you support.
